"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/browser";

const days = [["mon","Segunda"],["tue","Terça"],["wed","Quarta"],["thu","Quinta"],["fri","Sexta"],["sat","Sábado"],["sun","Domingo"]] as const;
const paymentLabels: Record<string,string> = { cash:"Dinheiro", credit:"Cartão de crédito", debit:"Cartão de débito", pix:"Pix" };

type Slot={start:string;end:string};
type Schedule=Record<string,{enabled:boolean;allDay:boolean;slots:Slot[]}>;
type Price={minutes:number;price:number};

const initialSchedule:Schedule=Object.fromEntries(days.map(([key])=>[key,{enabled:false,allDay:false,slots:[{start:"09:00",end:"18:00"}]}]));

export default function OperationalPage(){
 const supabase=useMemo(()=>createClient(),[]); const [profile,setProfile]=useState<any>(null); const [schedule,setSchedule]=useState<Schedule>(initialSchedule); const [prices,setPrices]=useState<Price[]>([{minutes:15,price:0}]); const [payments,setPayments]=useState<Record<string,boolean>>({cash:false,credit:false,debit:false,pix:false}); const [creditFee,setCreditFee]=useState(0); const [location,setLocation]=useState<any>(null); const [busy,setBusy]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login";return;} const [{data:p},{data:a}]=await Promise.all([supabase.from("advertiser_profiles").select("id,title,pricing,payment_options,availability").eq("user_id",user.id).maybeSingle(),supabase.from("user_addresses").select("zipcode,street,number,complement,city_id,state_id,latitude,longitude,location_visibility,public_latitude,public_longitude").eq("user_id",user.id).eq("address_type","primary").maybeSingle()]); if(p){setProfile(p);const pr=p.pricing&&typeof p.pricing==="object"?p.pricing:{};const po=p.payment_options&&typeof p.payment_options==="object"?p.payment_options:{};if(Array.isArray(pr.periods)&&pr.periods.length)setPrices(pr.periods.map((x:any)=>({minutes:Number(x.minutes)||15,price:Number(x.price)||0})));if(po.methods&&typeof po.methods==="object")setPayments(po.methods);setCreditFee(Number(po.credit_fee_percent)||0);if(pr.schedule) setSchedule({...initialSchedule,...pr.schedule});}setLocation(a||null);setBusy(false);})()},[supabase]);
 const toggleDay=(key:string)=>setSchedule(s=>({...s,[key]:{...s[key],enabled:!s[key].enabled}}));
 const setDay=(key:string,patch:any)=>setSchedule(s=>({...s,[key]:{...s[key],...patch}}));
 const save=async()=>{if(!profile){setError("Crie o rascunho do anúncio primeiro.");return;}setSaving(true);setError("");setMessage("");const pricing={periods:prices.filter(p=>p.minutes>0&&p.price>=0).map(p=>({minutes:p.minutes,price:Number(p.price.toFixed(2))})),schedule};const payment_options={methods:payments,credit_fee_percent:payments.credit?Number(creditFee.toFixed(2)):0};const {error:e}=await supabase.from("advertiser_profiles").update({pricing,payment_options,availability:JSON.stringify(schedule)}).eq("id",profile.id);if(e)setError(e.message);else setMessage("Configuração operacional salva com sucesso.");setSaving(false);};
 const submit=async()=>{if(!profile)return;setSaving(true);setError("");const r=await fetch("/api/painel/anuncio/enviar-analise",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile_id:profile.id})});const data=await r.json().catch(()=>({}));if(!r.ok)setError(data.error||"Não foi possível enviar para análise.");else setMessage("Anúncio enviado para análise da equipe Pecatho.");setSaving(false);};
 if(busy)return <main className="shell"><section className="hero"><h1>Carregando configuração...</h1></section></main>;
 return <main className="shell"><nav className="topbar"><div className="brand"><span className="brandMark">P</span><span>Pecatho</span></div><Link href="/painel/anuncio" className="navCta">Voltar ao anúncio</Link></nav><section className="hero" style={{maxWidth:1200}}><div className="eyebrow">CONFIGURAÇÃO OPERACIONAL</div><h1>Disponibilidade, <em>preços e pagamentos.</em></h1><p className="heroCopy">Defina quando você atende, os períodos de referência e as formas de pagamento. Essas informações ficam vinculadas ao mesmo anúncio e podem ser revisadas antes do envio para análise.</p>{message&&<p className="formSuccess">{message}</p>}{error&&<p className="formError">{error}</p>}
 <section className="authCard"><h2>Disponibilidade</h2><p className="fieldNote">Marque os dias em que atende. “24 horas” elimina a necessidade de informar horários naquele dia.</p>{days.map(([key,label])=><div key={key} className="serviceCheck" style={{alignItems:"center",flexWrap:"wrap"}}><label style={{display:"flex",gap:8,alignItems:"center",minWidth:150}}><input type="checkbox" checked={schedule[key].enabled} onChange={()=>toggleDay(key)}/><strong>{label}</strong></label>{schedule[key].enabled&&<><label><input type="checkbox" checked={schedule[key].allDay} onChange={e=>setDay(key,{allDay:e.target.checked})}/> 24 horas</label>{!schedule[key].allDay&&<><input type="time" value={schedule[key].slots[0]?.start||"09:00"} onChange={e=>setDay(key,{slots:[{...schedule[key].slots[0],start:e.target.value}]})}/><span>até</span><input type="time" value={schedule[key].slots[0]?.end||"18:00"} onChange={e=>setDay(key,{slots:[{...schedule[key].slots[0],end:e.target.value}]})}/></>}</>}</div>)}</section>
 <section className="authCard"><h2>Preços por período</h2><p className="fieldNote">O valor é associado ao período escolhido. O primeiro período pode ser 15 minutos e você pode adicionar quantos períodos forem necessários.</p>{prices.map((p,i)=><div key={i} className="formGrid"><label>Período<select value={p.minutes} onChange={e=>setPrices(v=>v.map((x,j)=>j===i?{...x,minutes:Number(e.target.value)}:x))}>{[15,20,30,45,60,90,120,180,240].map(n=><option key={n} value={n}>{n} minutos</option>)}</select></label><label>Preço (R$)<input type="number" min="0" step="0.01" value={p.price} onChange={e=>setPrices(v=>v.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/></label>{prices.length>1&&<button type="button" className="secondaryButton" onClick={()=>setPrices(v=>v.filter((_,j)=>j!==i))}>Remover</button>}</div>)}<button type="button" className="secondaryButton" onClick={()=>setPrices(v=>[...v,{minutes:30,price:0}])}>Adicionar período</button></section>
 <section className="authCard"><h2>Formas de pagamento</h2><div className="serviceList">{Object.entries(paymentLabels).map(([key,label])=><label key={key} className="serviceCheck"><span><input type="checkbox" checked={Boolean(payments[key])} onChange={e=>setPayments(v=>({...v,[key]:e.target.checked}))}/> {label}</span></label>)}</div>{payments.credit&&<label>Taxa adicional no crédito (%)<input type="number" min="0" step="0.01" value={creditFee} onChange={e=>setCreditFee(Number(e.target.value))}/><small className="fieldNote">A taxa é informativa para o anúncio. A cobrança real continuará sendo processada pelo fluxo financeiro seguro da plataforma.</small></label>}</section>
 <section className="authCard"><h2>Localização</h2>{location?<><p><strong>CEP:</strong> {location.zipcode||"—"} · {location.street||"—"}, {location.number||"—"}</p><p><strong>Visibilidade pública:</strong> {location.location_visibility||"private"}</p>{location.latitude&&location.longitude?<iframe className="mapFrame" title="Mapa da localização" loading="lazy" src={`https://www.google.com/maps?q=${location.latitude},${location.longitude}&z=15&output=embed`}/>:<p className="fieldNote">O mapa será disponibilizado assim que o endereço for geocodificado no editor do anúncio.</p>}</>:<p>Cadastre a localização no editor do anúncio. Ela pode ser configurada antes da publicação.</p>}<Link className="secondaryButton" href="/painel/anuncio">Editar localização</Link></section>
 <section className="authCard"><h2>Revisão e envio</h2><p>Salve as configurações e depois envie o rascunho para análise. A publicação definitiva permanece sob controle da moderação.</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button type="button" className="secondaryButton" disabled={saving} onClick={save}>Salvar configuração</button><button type="button" className="primaryButton" disabled={saving||!profile} onClick={submit}>Enviar para análise</button></div></section>
 </section></main>;
}
