import { notFound } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import LeadForm from "./LeadForm";

type PublicPartnerVenue={id:string;name:string;slug:string;venue_type:string;description:string|null;phone:string|null;website_url:string|null;instagram_url:string|null;state_id:number|null;city_id:number|null;tagline:string|null;highlights:string|null;recruitment_enabled:boolean;recruitment_title:string|null;recruitment_description:string|null;recruitment_contact_phone:string|null;recruitment_contact_email:string|null;recruitment_contact_whatsapp:string|null};
type PublicPartnerVenueMedia={id:string;kind:string;preview_storage_bucket:string|null;preview_storage_path:string|null;original_filename:string|null;is_primary:boolean;sort_order:number;width:number|null;height:number|null}; type PublicPartnerVenueRoom={id:string;name:string;description:string|null;available_slots:number;daily_rate:number|null;weekly_rate:number|null;monthly_rate:number|null;minimum_period:string|null;notes:string|null};
const types:Record<string,string>={nightclub:"Casa noturna",club:"Boate / clube",bar:"Bar",lounge:"Lounge",event_space:"Espaço para eventos",cabaret:"Cabaré",other:"Outro"};
const dayNames=["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"];
export const dynamic="force-dynamic";
function brl(value:number|null){if(value===null||value===undefined)return "";return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);}
function dateTime(value:string){return new Intl.DateTimeFormat("pt-BR",{dateStyle:"full",timeStyle:"short"}).format(new Date(value));}

export default async function ParceiroDetalhe({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const supabase=await createClient();
 const {data:vData}=await supabase.rpc("get_public_partner_venues",{p_slug:slug});
 const v=(vData as PublicPartnerVenue[]|null)?.[0]||null;
 if(!v)notFound();
 let city="",state="";
 if(v.city_id){const {data}=await supabase.from("cities").select("name,state_id").eq("id",v.city_id).maybeSingle();city=data?.name||"";if(data?.state_id){const {data:s}=await supabase.from("states").select("name,uf").eq("id",data.state_id).maybeSingle();state=s?.uf||s?.name||"";}}
 const [{data:media},{data:hours},{data:services},{data:events},{data:amenities},{data:rates},{data:roomsData}]=await Promise.all([
  supabase.rpc("get_public_partner_venue_media",{p_venue_id:v.id}),
  supabase.from("partner_venue_hours").select("weekday,open_time,close_time,is_closed").eq("venue_id",v.id).order("weekday"),
  supabase.from("partner_venue_services").select("id,name,description,price_from").eq("venue_id",v.id).eq("active",true).order("sort_order"),
  supabase.from("partner_venue_events").select("id,title,description,starts_at,ends_at,price_from").eq("venue_id",v.id).eq("status","published").gte("starts_at",new Date().toISOString()).order("starts_at").limit(12),
  supabase.from("partner_venue_amenities").select("id,name,description,icon_key").eq("venue_id",v.id).eq("active",true).order("sort_order"),
  supabase.from("partner_venue_rates").select("id,period_type,label,price,minimum_nights,notes").eq("venue_id",v.id).eq("active",true).order("sort_order"),
  supabase.from("partner_venue_rooms").select("id,name,description,available_slots,daily_rate,weekly_rate,monthly_rate,minimum_period,notes").eq("venue_id",v.id).eq("active",true).eq("status","published").order("sort_order")
 ]);
 const publicMedia=(media||[]) as PublicPartnerVenueMedia[];
 const gallery=publicMedia.map(m=>{const previewUrl=m.preview_storage_bucket&&m.preview_storage_path?supabase.storage.from(m.preview_storage_bucket).getPublicUrl(m.preview_storage_path).data.publicUrl||null:null;return previewUrl?{...m,url:previewUrl}:null;}).filter((m):m is NonNullable<typeof m>=>m!==null);
 const rooms=((roomsData||[]) as PublicPartnerVenueRoom[]).filter(r=>Number(r.available_slots)>0); const location=city+(state?" · "+state:""); const recruitmentWhatsapp=v.recruitment_contact_whatsapp?String(v.recruitment_contact_whatsapp).replace(/\D/g,""): ""; const partnerWhatsapp=v.phone?String(v.phone).replace(/\D/g,""): "";
 return <main className="shell partnerDetail">
  <nav className="topbar"><Link className="brand" href="/"><span className="brandMark">P</span><span>Pecatho</span></Link><div className="navLinks"><Link href="/parceiros">Parceiros</Link><Link href="/anunciantes">Anunciantes</Link><Link href="/fans">Fans</Link></div></nav>
  <section className="hero" style={{position:"relative",overflow:"hidden"}}><div style={{position:"absolute",inset:0,pointerEvents:"none",background:"radial-gradient(circle at 80% 10%,rgba(124,58,237,.28),transparent 35%),radial-gradient(circle at 10% 100%,rgba(231,195,63,.12),transparent 32%)"}}/><div style={{position:"relative"}}><div className="eyebrow">{types[v.venue_type]||"PARCEIRO PECATHO"}</div><h1>{v.name}</h1>{v.tagline&&<p style={{fontSize:"clamp(1rem,2vw,1.25rem)",fontWeight:800,maxWidth:760,margin:"10px 0",color:"#e9d5ff"}}>{v.tagline}</p>}<p className="heroCopy">{v.description||"Perfil oficial do parceiro Pecatho."}</p>{v.highlights&&<div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:18}}>{v.highlights.split(/[,\\n]+/).map((item:string,i:number)=>item.trim()?<span key={i} style={{padding:"8px 11px",borderRadius:999,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.05)",fontSize:12,fontWeight:800}}>{item.trim()}</span>:null)}</div>}<div className="partnerFacts" style={{marginTop:18}}><span>{location||"Localização não informada"}</span>{v.phone&&<span>{v.phone}</span>}</div><div className="heroActions">{v.website_url&&<a className="primaryButton" href={v.website_url} target="_blank" rel="noreferrer">Site oficial</a>}{v.instagram_url&&<a className="secondaryButton" href={v.instagram_url} target="_blank" rel="noreferrer">Instagram</a>}{v.phone&&<><a className="secondaryButton" href={"tel:"+v.phone}>Ligar</a><a className="secondaryButton" href={"https://wa.me/"+partnerWhatsapp} target="_blank" rel="noreferrer">WhatsApp</a></>}{v.recruitment_enabled&&<a className="secondaryButton" href="#trabalhe-conosco">Trabalhe com a casa</a>}<Link className="secondaryButton" href="/parceiros">Voltar aos parceiros</Link></div></div></section>
  {gallery.length>0&&<section className="authCard"><div className="eyebrow">GALERIA OFICIAL</div><h2>A casa por dentro e por fora.</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:14,marginTop:18}}>{gallery.map(m=>m.kind==="image"?<img key={m.id} src={m.url} alt={m.original_filename||v.name} style={{width:"100%",aspectRatio:"16/10",objectFit:"cover",borderRadius:14}}/>:<video key={m.id} src={m.url} controls style={{width:"100%",aspectRatio:"16/10",objectFit:"cover",borderRadius:14}}/>)}</div></section>}
  {(amenities||[]).length>0&&<section id="estrutura" className="authCard"><div className="eyebrow">ESTRUTURA</div><h2>Recursos disponíveis</h2><p style={{opacity:.75}}>Tudo o que o parceiro disponibiliza para tornar a experiência mais confortável.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12,marginTop:18}}>{(amenities||[]).map(a=><article key={a.id} style={{padding:16,border:"1px solid rgba(255,255,255,.08)",borderRadius:16,background:"rgba(255,255,255,.025)"}}><div style={{fontSize:22,marginBottom:8}}>✓</div><strong>{a.name}</strong>{a.description&&<p style={{opacity:.7,lineHeight:1.5,marginBottom:0}}>{a.description}</p>}</article>)}</div></section>}
  {rooms.length>0&&<section id="espacos-profissionais" className="authCard"><div className="eyebrow">ESPAÇOS PARA PROFISSIONAIS</div><h2>Quartos e vagas para atendimentos presenciais</h2><p style={{opacity:.75,lineHeight:1.6}}>Condições informadas pelo parceiro para acompanhantes que desejam realizar atendimentos presenciais na casa. O contato e a contratação são feitos diretamente com o parceiro.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14,marginTop:18}}>{rooms.map(r=>{const message=encodeURIComponent("Olá! Vi no Pecatho o espaço "+r.name+" da casa "+v.name+" e gostaria de consultar disponibilidade e condições.");const roomContactWhatsapp=partnerWhatsapp||(v.recruitment_enabled?recruitmentWhatsapp:"");const whatsapp=roomContactWhatsapp?"https://wa.me/"+roomContactWhatsapp+"?text="+message:null;return <article key={r.id} style={{padding:20,border:"1px solid rgba(231,195,63,.22)",borderRadius:18,background:"linear-gradient(145deg,rgba(231,195,63,.07),rgba(255,255,255,.025))"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"}}><div><small style={{opacity:.65,textTransform:"uppercase",fontWeight:800}}>Espaço profissional</small><h3 style={{margin:"6px 0"}}>{r.name}</h3></div><strong style={{fontSize:20}}>{r.available_slots} vaga{r.available_slots===1?"":"s"}</strong></div>{r.description&&<p style={{opacity:.75,lineHeight:1.55}}>{r.description}</p>}<div style={{display:"grid",gap:6,fontSize:14}}>{r.daily_rate!=null&&<span>Diária: <strong>{brl(Number(r.daily_rate))}</strong></span>}{r.weekly_rate!=null&&<span>Semanal: <strong>{brl(Number(r.weekly_rate))}</strong></span>}{r.monthly_rate!=null&&<span>Mensal: <strong>{brl(Number(r.monthly_rate))}</strong></span>}</div>{r.minimum_period&&<p style={{opacity:.7}}>Mínimo: {r.minimum_period}</p>}{r.notes&&<p style={{opacity:.7,lineHeight:1.5}}>{r.notes}</p>}{whatsapp&&<div style={{marginTop:14}}><a className="primaryButton" href={whatsapp} target="_blank" rel="noreferrer">Consultar disponibilidade</a></div>}</article>})}</div></section>}
  {(rates||[]).length>0&&<section id="condicoes-profissionais" className="authCard"><div className="eyebrow">CONDIÇÕES PARA PROFISSIONAIS</div><h2>Diárias e temporadas</h2><p style={{opacity:.75}}>Consulte as condições informadas pelo parceiro para profissionais que desejam trabalhar na casa.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14,marginTop:18}}>{(rates||[]).map(r=><article key={r.id} style={{padding:18,border:"1px solid rgba(231,195,63,.2)",borderRadius:16,background:"rgba(231,195,63,.04)"}}><small style={{opacity:.65,textTransform:"uppercase"}}>{r.period_type}</small><h3 style={{margin:"6px 0"}}>{r.label}</h3><strong style={{fontSize:22}}>{brl(Number(r.price))}</strong>{r.minimum_nights&&<p style={{opacity:.7}}>Mínimo de {r.minimum_nights} noite(s).</p>}{r.notes&&<p style={{opacity:.75,lineHeight:1.5}}>{r.notes}</p>}</article>)}</div></section>}
  {(hours||[]).length>0&&<section className="authCard"><div className="eyebrow">HORÁRIOS</div><h2>Funcionamento</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginTop:18}}>{(hours||[]).map(h=><div key={h.weekday} style={{padding:14,border:"1px solid rgba(255,255,255,.08)",borderRadius:12}}><strong>{dayNames[h.weekday]||"Dia"}</strong><div style={{marginTop:6,opacity:.75}}>{h.is_closed?"Fechado":(h.open_time&&h.close_time?h.open_time.slice(0,5)+" às "+h.close_time.slice(0,5):"Horário não informado")}</div></div>)}</div></section>}
  {(services||[]).length>0&&<section className="authCard"><div className="eyebrow">SERVIÇOS</div><h2>O que a casa oferece</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:14,marginTop:18}}>{(services||[]).map(s=><article key={s.id} style={{padding:18,border:"1px solid rgba(255,255,255,.08)",borderRadius:14}}><h3 style={{margin:0}}>{s.name}</h3>{s.description&&<p style={{opacity:.75,lineHeight:1.6}}>{s.description}</p>}{s.price_from!==null&&<strong>A partir de {brl(Number(s.price_from))}</strong>}</article>)}</div></section>}
  {(events||[]).length>0&&<section className="authCard"><div className="eyebrow">AGENDA</div><h2>Próximos eventos</h2><div style={{display:"grid",gap:14,marginTop:18}}>{(events||[]).map(e=>{const message=encodeURIComponent("Olá! Vi o evento "+e.title+" no Pecatho e gostaria de obter mais informações.");const whatsapp=v.phone?"https://wa.me/"+String(v.phone).replace(/\D/g,"")+"?text="+message:null;return <article key={e.id} style={{padding:18,border:"1px solid rgba(255,255,255,.08)",borderRadius:14}}><h3 style={{margin:"0 0 8px"}}>{e.title}</h3><div style={{opacity:.8}}>{dateTime(e.starts_at)}{e.ends_at?" · até "+new Intl.DateTimeFormat("pt-BR",{timeStyle:"short"}).format(new Date(e.ends_at)):""}</div>{e.description&&<p style={{opacity:.75,lineHeight:1.6}}>{e.description}</p>}{e.price_from!==null&&<strong>A partir de {brl(Number(e.price_from))}</strong>}{whatsapp&&<div style={{marginTop:14}}><a className="secondaryButton" href={whatsapp} target="_blank" rel="noreferrer">Quero informações</a></div>}</article>})}</div></section>}
  {v.recruitment_enabled&&<section id="trabalhe-conosco" className="authCard"><div className="eyebrow">OPORTUNIDADES</div><h2>{v.recruitment_title||"Trabalhe com esta casa"}</h2><p style={{opacity:.75,lineHeight:1.6}}>{v.recruitment_description||"O parceiro recebe contatos de profissionais interessadas em conhecer suas condições de trabalho."}</p><div className="heroActions" style={{marginTop:16}}>{recruitmentWhatsapp&&<a className="primaryButton" href={"https://wa.me/"+recruitmentWhatsapp+"?text="+encodeURIComponent("Olá! Encontrei a oportunidade para profissionais no Pecatho e gostaria de conhecer as condições para trabalhar com a casa.")} target="_blank" rel="noreferrer">Falar pelo WhatsApp</a>}{v.recruitment_contact_phone&&<a className="secondaryButton" href={"tel:"+v.recruitment_contact_phone}>Ligar</a>}{v.recruitment_contact_email&&<a className="secondaryButton" href={"mailto:"+v.recruitment_contact_email}>Enviar e-mail</a>}</div><p style={{fontSize:12,opacity:.55,marginTop:14}}>O Pecatho não publica automaticamente contatos pessoais de acompanhantes; esta área apresenta apenas os canais fornecidos pelo parceiro.</p></section>}
  <div className="partnerMobileActions" aria-label="Ações rápidas do parceiro">
   {v.recruitment_enabled ? <a className="primaryButton" href="#trabalhe-conosco">Trabalhe aqui</a> : v.phone ? <a className="primaryButton" href={"https://wa.me/"+partnerWhatsapp+"?text="+encodeURIComponent("Olá! Encontrei esta casa no Pecatho e gostaria de obter informações.")} target="_blank" rel="noreferrer">WhatsApp</a> : <a className="primaryButton" href="#contato">Contato</a>}
   <a className="secondaryButton" href="#estrutura">Estrutura</a>
   <a className="secondaryButton" href="#condicoes-profissionais">Valores</a>
  </div>
    <section id="contato"><LeadForm venueId={v.id}/></section>
  <section className="authCard" style={{textAlign:"center"}}><div className="eyebrow">PECATHO</div><h2>Quer falar com a casa?</h2><p style={{opacity:.75}}>Use os canais oficiais acima para consultar reservas, serviços, eventos e outras informações.</p></section>
 </main>;
}