"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/browser";

const weekdays=[[0,"Domingo"],[1,"Segunda-feira"],[2,"Terça-feira"],[3,"Quarta-feira"],[4,"Quinta-feira"],[5,"Sexta-feira"],[6,"Sábado"]] as const;
type Hour={id:string;weekday:number;open_time:string|null;close_time:string|null;is_closed:boolean};
type Service={id:string;name:string;description:string|null;price_from:number|null;active:boolean;sort_order:number};
type Event={id:string;title:string;description:string|null;starts_at:string;ends_at:string|null;price_from:number|null;status:string};
const money=(v:number|null)=>v==null?"":v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function ParceiroComercial(){
 const [venueId,setVenueId]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [hours,setHours]=useState<Hour[]>([]);const [services,setServices]=useState<Service[]>([]);const [events,setEvents]=useState<Event[]>([]);
 const [serviceName,setServiceName]=useState("");const [serviceDesc,setServiceDesc]=useState("");const [servicePrice,setServicePrice]=useState("");
 const [eventTitle,setEventTitle]=useState("");const [eventDesc,setEventDesc]=useState("");const [eventStart,setEventStart]=useState("");const [eventEnd,setEventEnd]=useState("");const [eventPrice,setEventPrice]=useState("");
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return}const {data:v,error:e}=await s.from("partner_venues").select("id").eq("owner_user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(e)throw e;if(!v)throw new Error("Cadastre a casa antes de configurar a área comercial.");setVenueId(v.id);const [h,sv,ev]=await Promise.all([s.from("partner_venue_hours").select("*").eq("venue_id",v.id).order("weekday"),s.from("partner_venue_services").select("*").eq("venue_id",v.id).order("sort_order"),s.from("partner_venue_events").select("*").eq("venue_id",v.id).order("starts_at")]);if(h.error)throw h.error;if(sv.error)throw sv.error;if(ev.error)throw ev.error;setHours((h.data||[]) as Hour[]);setServices((sv.data||[]) as Service[]);setEvents((ev.data||[]) as Event[])}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar o comercial."))},[]);
 async function saveHours(){if(!venueId)return;setBusy(true);setError("");try{const s=createClient();for(const day of weekdays){const h=hours.find(x=>x.weekday===day[0]);const payload={venue_id:venueId,weekday:day[0],open_time:h?.open_time||null,close_time:h?.close_time||null,is_closed:h?.is_closed??true};const {error:e}=await s.from("partner_venue_hours").upsert(payload,{onConflict:"venue_id,weekday"});if(e)throw e}setMessage("Horários salvos.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar os horários.")}finally{setBusy(false)}}
 function setHour(day:number,key:keyof Hour,value:string|boolean){setHours(prev=>{const current=prev.find(x=>x.weekday===day)||{id:"",weekday:day,open_time:null,close_time:null,is_closed:true};return [...prev.filter(x=>x.weekday!==day),{...current,[key]:value}]})}
 async function addService(e:FormEvent){e.preventDefault();if(!venueId||!serviceName.trim())return;setBusy(true);setError("");try{const {error:e}=await createClient().from("partner_venue_services").insert({venue_id:venueId,name:serviceName.trim(),description:serviceDesc.trim()||null,price_from:servicePrice?Number(servicePrice.replace(",",".")):null,sort_order:services.length});if(e)throw e;setServiceName("");setServiceDesc("");setServicePrice("");await load();setMessage("Serviço adicionado.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível adicionar o serviço.")}finally{setBusy(false)}}
 async function toggleService(x:Service){setBusy(true);try{const {error:e}=await createClient().from("partner_venue_services").update({active:!x.active}).eq("id",x.id);if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível alterar o serviço.")}finally{setBusy(false)}}
 async function removeService(id:string){setBusy(true);try{const {error:e}=await createClient().from("partner_venue_services").delete().eq("id",id);if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível remover o serviço.")}finally{setBusy(false)}}
 async function addEvent(e:FormEvent){e.preventDefault();if(!venueId||!eventTitle.trim()||!eventStart)return;setBusy(true);setError("");try{const {error:e}=await createClient().from("partner_venue_events").insert({venue_id:venueId,title:eventTitle.trim(),description:eventDesc.trim()||null,starts_at:new Date(eventStart).toISOString(),ends_at:eventEnd?new Date(eventEnd).toISOString():null,price_from:eventPrice?Number(eventPrice.replace(",",".")):null,status:"draft"});if(e)throw e;setEventTitle("");setEventDesc("");setEventStart("");setEventEnd("");setEventPrice("");await load();setMessage("Evento salvo como rascunho. Publique quando estiver pronto.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível adicionar o evento.")}finally{setBusy(false)}}
 async function publishEvent(x:Event){setBusy(true);try{const {error:e}=await createClient().from("partner_venue_events").update({status:x.status==="published"?"draft":"published"}).eq("id",x.id);if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível alterar o evento.")}finally{setBusy(false)}}
 async function removeEvent(id:string){setBusy(true);try{const {error:e}=await createClient().from("partner_venue_events").delete().eq("id",id);if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível remover o evento.")}finally{setBusy(false)}}
 return <main className="shell"><nav className="topbar"><Link className="brand" href="/"><span className="brandMark">P</span><span>Pecatho</span></Link><div className="navLinks"><Link href="/painel/parceiro">Dados da casa</Link><Link href="/painel/parceiro/midias">Galeria</Link><Link href="/parceiros">Vitrine</Link></div></nav><section className="hero"><div className="eyebrow">PARCEIROS · COMERCIAL</div><h1>Transforme o perfil em uma <em>vitrine comercial.</em></h1><p className="heroCopy">Horários, serviços e eventos ficam vinculados à sua casa e aparecem no perfil público quando publicados.</p>{error&&<p className="formError">{error}</p>}{message&&<p className="formSuccess">{message}</p>}
 <section className="authCard"><div className="eyebrow">HORÁRIOS</div><h2>Funcionamento</h2><div className="partnerGrid">{weekdays.map(([day,label])=>{const h=hours.find(x=>x.weekday===day);return <div className="card" key={day}><strong>{label}</strong><label className="checkRow"><input type="checkbox" checked={h?.is_closed??true} onChange={e=>setHour(day,"is_closed",e.target.checked)}/> Fechado</label>{!(h?.is_closed??true)&&<div className="formGrid"><label>Abertura<input type="time" value={h?.open_time||""} onChange={e=>setHour(day,"open_time",e.target.value)}/></label><label>Fechamento<input type="time" value={h?.close_time||""} onChange={e=>setHour(day,"close_time",e.target.value)}/></label></div>}</div>})}</div><button className="primaryButton" disabled={busy} onClick={()=>void saveHours()}>Salvar horários</button></section>
 <section className="authCard"><div className="eyebrow">SERVIÇOS</div><h2>O que sua casa oferece</h2><form onSubmit={addService}><div className="formGrid"><label>Nome<input value={serviceName} onChange={e=>setServiceName(e.target.value)} required/></label><label>Preço a partir de<input value={servicePrice} onChange={e=>setServicePrice(e.target.value)} inputMode="decimal" placeholder="Ex.: 50,00"/></label></div><label>Descrição<textarea rows={3} value={serviceDesc} onChange={e=>setServiceDesc(e.target.value)} /></label><button className="primaryButton" disabled={busy}>Adicionar serviço</button></form>{services.map(x=><div className="card" key={x.id}><strong>{x.name}</strong><p>{x.description||""}</p><span>{x.price_from!=null?"A partir de "+money(x.price_from):"Preço sob consulta"}</span><div style={{display:"flex",gap:8,marginTop:10}}><button className="secondaryButton" type="button" disabled={busy} onClick={()=>void toggleService(x)}>{x.active?"Desativar":"Ativar"}</button><button className="secondaryButton" type="button" disabled={busy} onClick={()=>void removeService(x.id)}>Remover</button></div></div>)}</section>
 <section className="authCard"><div className="eyebrow">EVENTOS</div><h2>Agenda da casa</h2><form onSubmit={addEvent}><label>Título<input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} required/></label><label>Descrição<textarea rows={3} value={eventDesc} onChange={e=>setEventDesc(e.target.value)} /></label><div className="formGrid"><label>Início<input type="datetime-local" value={eventStart} onChange={e=>setEventStart(e.target.value)} required/></label><label>Fim<input type="datetime-local" value={eventEnd} onChange={e=>setEventEnd(e.target.value)}/></label><label>Preço a partir de<input value={eventPrice} onChange={e=>setEventPrice(e.target.value)} inputMode="decimal" placeholder="Ex.: 30,00"/></label></div><button className="primaryButton" disabled={busy}>Criar evento</button></form>{events.map(x=><div className="card" key={x.id}><strong>{x.title}</strong><p>{x.description||""}</p><p>{new Date(x.starts_at).toLocaleString("pt-BR")}{x.ends_at?" → "+new Date(x.ends_at).toLocaleString("pt-BR"):""}</p><span>{x.price_from!=null?"A partir de "+money(x.price_from):"Preço sob consulta"} · {x.status==="published"?"Publicado":"Rascunho"}</span><div style={{display:"flex",gap:8,marginTop:10}}><button className="secondaryButton" type="button" disabled={busy} onClick={()=>void publishEvent(x)}>{x.status==="published"?"Despublicar":"Publicar"}</button><button className="secondaryButton" type="button" disabled={busy} onClick={()=>void removeEvent(x.id)}>Remover</button></div></div>)}</section>
 </section></main>
}