"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/browser";

type StateRow = { id: number; uf: string; name: string };
type CityRow = { id: number; name: string; state_id?: number | null };
type CategoryRow = { id: number; name: string };
type AttributeRow = { id: string; name: string; slug: string; field_type: string; options: unknown; required: boolean; display_public: boolean; sort_order: number };
type ServiceRow = { id: string; name: string; slug: string; description: string | null; required: boolean; display_public: boolean; sort_order: number };

const sections = ["Apresentação", "Localização", "Características", "Serviços", "Preços", "Publicação"];

function optionsOf(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is string => typeof item === "string");
}

export default function AnuncioPage() {
  const [active, setActive] = useState("Apresentação");
  const [title, setTitle] = useState(""); const [name, setName] = useState(""); const [summary, setSummary] = useState(""); const [description, setDescription] = useState("");
  const [stateId, setStateId] = useState(""); const [cityId, setCityId] = useState(""); const [categoryId, setCategoryId] = useState(""); const [price, setPrice] = useState(""); const [servicesText, setServicesText] = useState("");
  const [zipcode, setZipcode] = useState(""); const [street, setStreet] = useState(""); const [number, setNumber] = useState(""); const [complement, setComplement] = useState(""); const [neighborhood, setNeighborhood] = useState(""); const [cepBusy, setCepBusy] = useState(false); const [latitude, setLatitude] = useState<number | null>(null); const [longitude, setLongitude] = useState<number | null>(null); const [locationMessage, setLocationMessage] = useState("");
  const [states, setStates] = useState<StateRow[]>([]); const [cities, setCities] = useState<CityRow[]>([]); const [categories, setCategories] = useState<CategoryRow[]>([]); const [attributes, setAttributes] = useState<AttributeRow[]>([]); const [services, setServices] = useState<ServiceRow[]>([]);
  const [attributeValues, setAttributeValues] = useState<Record<string, string | string[] | boolean | number | null>>({}); const [selectedServices, setSelectedServices] = useState<Record<string, boolean>>({});
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");

  const supabase = useMemo(() => createClient(), []);

  useEffect(() => { (async () => {
    const { data: s } = await supabase.from("states").select("id,uf,name").order("name"); setStates((s || []) as StateRow[]);
    const { data: c } = await supabase.from("categories").select("id,name").order("name"); setCategories((c || []) as CategoryRow[]);
    const { data: profile } = await supabase.from("advertiser_profiles").select("id,title,display_name,summary,description,state_id,city_id,category_id,pricing,service_options").maybeSingle();
    if (profile) { setTitle(profile.title || ""); setName(profile.display_name || ""); setSummary(profile.summary || ""); setDescription(profile.description || ""); setStateId(profile.state_id ? String(profile.state_id) : ""); setCityId(profile.city_id ? String(profile.city_id) : ""); setCategoryId(profile.category_id ? String(profile.category_id) : ""); setPrice(profile.pricing?.price ? String(profile.pricing.price) : ""); setServicesText(profile.service_options?.description || ""); }
    const { data: address } = await supabase.from("user_addresses").select("zipcode,street,number,complement,city_id,state_id,latitude,longitude").eq("address_type","primary").maybeSingle();
    if (address) { setZipcode(address.zipcode || ""); setStreet(address.street || ""); setNumber(address.number || ""); setComplement(address.complement || ""); setLatitude(address.latitude == null ? null : Number(address.latitude)); setLongitude(address.longitude == null ? null : Number(address.longitude)); }
    setLoading(false);
  })(); }, [supabase]);

  useEffect(() => { if (!stateId) { setCities([]); return; } (async () => { const { data } = await supabase.from("cities").select("id,name,state_id").eq("state_id", Number(stateId)).order("name"); setCities((data || []) as CityRow[]); })(); }, [stateId, supabase]);

  useEffect(() => { if (!categoryId) { setAttributes([]); setServices([]); setAttributeValues({}); setSelectedServices({}); return; } (async () => {
    const [a, s] = await Promise.all([
      supabase.from("category_attributes").select("id,name,slug,field_type,options,required,display_public,sort_order").eq("category_id", Number(categoryId)).order("sort_order"),
      supabase.from("category_services").select("id,name,slug,description,required,display_public,sort_order").eq("category_id", Number(categoryId)).order("sort_order"),
    ]);
    setAttributes((a.data || []) as AttributeRow[]); setServices((s.data || []) as ServiceRow[]); setAttributeValues({}); setSelectedServices({});
  })(); }, [categoryId, supabase]);

  async function lookupCep() { const cep = zipcode.replace(/\D/g, ""); setLocationMessage(""); if (cep.length !== 8) { setLocationMessage("Informe um CEP válido com 8 dígitos."); return; } setCepBusy(true); try { const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`); if (!response.ok) throw new Error("Não foi possível consultar o CEP."); const data = await response.json(); if (data.erro) throw new Error("CEP não encontrado."); setStreet(data.logradouro || ""); setNeighborhood(data.bairro || ""); const matchedState = states.find((s) => s.uf === data.uf); if (matchedState) { setStateId(String(matchedState.id)); const { data: cityRows } = await supabase.from("cities").select("id,name,state_id").eq("state_id", matchedState.id).eq("id", Number(data.ibge)); const city = cityRows?.[0]; if (city) setCityId(String(city.id)); else setLocationMessage("CEP encontrado, mas o município não foi localizado na base territorial do Pecatho."); } setLocationMessage(`CEP localizado: ${data.localidade} — ${data.uf}.`); } catch (err) { setLocationMessage(err instanceof Error ? err.message : "Não foi possível consultar o CEP."); } finally { setCepBusy(false); } }

  async function geolocateAddress() { setLocationMessage(""); if (!street || !number || !cityId || !stateId) { setLocationMessage("Preencha CEP, endereço, número, Estado e Cidade antes de localizar no mapa."); return; } setCepBusy(true); try { const city = cities.find((item) => item.id === Number(cityId)); const state = states.find((item) => item.id === Number(stateId)); const query = encodeURIComponent(`${street}, ${number}, ${city?.name || ""}, ${state?.uf || ""}, Brasil`); const response = await fetch(`/api/geocode?address=${query}`); if (!response.ok) throw new Error("Não foi possível localizar este endereço."); const result = await response.json(); if (!result?.latitude || !result?.longitude) throw new Error("Endereço não localizado. Confira o número e tente novamente."); setLatitude(Number(result.latitude)); setLongitude(Number(result.longitude)); setLocationMessage("Localização encontrada. O mapa público utilizará estas coordenadas."); } catch (err) { setLocationMessage(err instanceof Error ? err.message : "Não foi possível localizar o endereço."); } finally { setCepBusy(false); } }

  function setAttribute(id: string, value: string | string[] | boolean | number | null) { setAttributeValues((current) => ({ ...current, [id]: value })); }
  function toggleService(id: string, value: boolean) { setSelectedServices((current) => ({ ...current, [id]: value })); }

  async function submit(e: FormEvent) {
    e.preventDefault(); setBusy(true); setMessage(""); setError("");
    const { data: { user } } = await supabase.auth.getUser(); if (!user) { window.location.href = "/login"; return; }
    if (!categoryId) { setError("Selecione uma categoria antes de salvar."); setBusy(false); return; }
    const missing = attributes.filter((a) => {
      const value = attributeValues[a.id];
      return a.required && (value === undefined || value === "" || (Array.isArray(value) && value.length === 0));
    });
    if (missing.length) { setError(`Preencha os campos obrigatórios: ${missing.map((a) => a.name).join(", ")}.`); setBusy(false); return; }
    const requiredServices = services.filter((s) => s.required && selectedServices[s.id] !== true); if (requiredServices.length) { setError(`Selecione os serviços obrigatórios: ${requiredServices.map((s) => s.name).join(", ")}.`); setBusy(false); return; }
    const { data: old } = await supabase.from("advertiser_profiles").select("id").eq("user_id", user.id).maybeSingle();
    const normalizedPrice = price ? Number(price.replace(/\./g, "").replace(",", ".")) : null;
    const payload = { title, display_name: name, summary, description, state_id: stateId ? Number(stateId) : null, city_id: cityId ? Number(cityId) : null, category_id: Number(categoryId), pricing: { price: normalizedPrice }, service_options: { description: servicesText }, social_links: {}, payment_options: {} };
    const result = old ? await supabase.from("advertiser_profiles").update(payload).eq("id", old.id) : await supabase.from("advertiser_profiles").insert({ ...payload, user_id: user.id, status: "draft", verification_status: "unverified" }).select("id").single();
    if (result.error) { setError("Não foi possível salvar o anúncio. " + result.error.message); setBusy(false); return; }
    const profileId = old?.id || (result.data as { id: string } | null)?.id; if (!profileId) { setError("O perfil foi salvo, mas não foi possível identificar o anúncio."); setBusy(false); return; }
    const { error: clearAttrError } = await supabase.from("profile_attribute_values").delete().eq("profile_id", profileId); if (clearAttrError) { setError("Não foi possível atualizar as características do anúncio. " + clearAttrError.message); setBusy(false); return; }
    const attrs = attributes.filter((a) => attributeValues[a.id] !== undefined && attributeValues[a.id] !== "").map((a) => ({ profile_id: profileId, attribute_id: a.id, value: attributeValues[a.id] }));
    if (attrs.length) { const { error: attrError } = await supabase.from("profile_attribute_values").insert(attrs); if (attrError) { setError("Não foi possível salvar as características. " + attrError.message); setBusy(false); return; } }
    const { error: clearServiceError } = await supabase.from("profile_services").delete().eq("profile_id", profileId); if (clearServiceError) { setError("Não foi possível atualizar os serviços. " + clearServiceError.message); setBusy(false); return; }
    const selected = services.filter((s) => selectedServices[s.id] === true).map((s) => ({ profile_id: profileId, service_id: s.id, selected: true }));
    if (selected.length) { const { error: serviceError } = await supabase.from("profile_services").insert(selected); if (serviceError) { setError("Não foi possível salvar os serviços. " + serviceError.message); setBusy(false); return; } }
    if (zipcode || street || number) { const publicLatitude = latitude == null ? null : latitude + 0.002; const publicLongitude = longitude == null ? null : longitude + 0.002; const addressData = { zipcode: zipcode.replace(/\D/g, "").slice(0,8) || null, street: street || null, number: number || null, complement: complement || null, city_id: cityId ? Number(cityId) : null, state_id: stateId ? Number(stateId) : null, latitude, longitude, is_primary: true, location_visibility: "approximate", public_latitude: publicLatitude, public_longitude: publicLongitude }; const { data: existingAddress } = await supabase.from("user_addresses").select("id").eq("user_id", user.id).eq("is_primary", true).maybeSingle(); const addressResult = existingAddress ? await supabase.from("user_addresses").update(addressData).eq("id", existingAddress.id) : await supabase.from("user_addresses").insert({ ...addressData, user_id: user.id, address_type: "primary" }); if (addressResult.error) { setError("O anúncio foi salvo, mas não foi possível salvar a localização. " + addressResult.error.message); setBusy(false); return; } }
    setMessage("Rascunho salvo com sucesso."); setBusy(false);
  }

  if (loading) return <main className="shell"><section className="hero"><p>Carregando editor...</p></section></main>;
  return <main className="shell"><nav className="topbar"><div className="brand"><span className="brandMark">P</span><span>Pecatho</span></div><Link href="/painel" className="navCta">Painel</Link></nav><section className="hero"><div className="eyebrow">EDITOR DO ANÚNCIO</div><h1>Construa seu <em>perfil.</em></h1><p className="heroCopy">Preencha as informações com atenção. O anúncio permanece em rascunho até passar pelo processo de revisão e publicação.</p><div className="editorGrid"><aside className="editorNav">{sections.map((section) => <button key={section} type="button" className={`editorTab ${active === section ? "active" : ""}`} onClick={() => setActive(section)}>{section}</button>)}</aside><form className="authCard editorCard" onSubmit={submit}>
    {active === "Apresentação" && <><h2>Apresentação</h2><label>Categoria<select value={categoryId} onChange={(e) => setCategoryId(e.target.value)} required><option value="">Selecione uma categoria</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Título<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><label>Nome público<input value={name} onChange={(e) => setName(e.target.value)} required /></label><label>Resumo<textarea value={summary} onChange={(e) => setSummary(e.target.value)} rows={3} /></label><label>Descrição<textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={7} /></label></>}
    {active === "Localização" && <><h2>Localização</h2><p className="fieldNote">O CEP preenche automaticamente o endereço. O mapa público não exibirá o endereço residencial exato.</p><label>CEP<div style={{display:"flex",gap:8}}><input value={zipcode} onChange={(e) => setZipcode(e.target.value.replace(/\D/g,"").slice(0,8))} onBlur={() => { if (zipcode.replace(/\D/g,"").length === 8) lookupCep(); }} inputMode="numeric" placeholder="00000-000" /><button type="button" className="secondaryButton" onClick={lookupCep} disabled={cepBusy}>{cepBusy ? "Consultando..." : "Consultar CEP"}</button></div></label><label>Logradouro<input value={street} onChange={(e) => setStreet(e.target.value)} /></label><label>Número<input value={number} onChange={(e) => setNumber(e.target.value)} /></label><label>Complemento<input value={complement} onChange={(e) => setComplement(e.target.value)} /></label><label>Bairro<input value={neighborhood} readOnly /></label><label>Estado<select value={stateId} onChange={(e) => { setStateId(e.target.value); setCityId(""); }}><option value="">Selecione</option>{states.map((s) => <option key={s.id} value={s.id}>{s.name} — {s.uf}</option>)}</select></label><label>Cidade<select value={cityId} onChange={(e) => setCityId(e.target.value)} disabled={!stateId}><option value="">Selecione</option>{cities.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button type="button" className="secondaryButton" onClick={geolocateAddress} disabled={cepBusy}>{cepBusy ? "Localizando..." : "Localizar endereço no mapa"}</button>{locationMessage && <p className="fieldNote">{locationMessage}</p>}{latitude != null && longitude != null ? <div className="mapCard"><div className="mapHeader"><div><strong>Pré-visualização da localização</strong><span>O endereço exato não será exibido publicamente.</span></div><a href={`https://www.google.com/maps/search/?api=1&query=${latitude},${longitude}`} target="_blank" rel="noreferrer">Abrir no Google Maps</a></div><iframe className="mapFrame" title="Mapa da localização do anúncio" loading="lazy" src={`https://www.google.com/maps?q=${latitude},${longitude}&z=16&output=embed`} /></div> : <div className="mapPlaceholder"><strong>Mapa ainda não definido</strong><span>Consulte o CEP e localize o endereço para visualizar a posição.</span></div>}</>}
    {active === "Características" && <><h2>Características</h2>{!categoryId ? <p className="fieldNote">Escolha uma categoria na apresentação.</p> : attributes.length === 0 ? <p className="fieldNote">Esta categoria ainda não possui atributos configurados.</p> : attributes.map((a) => <label key={a.id}>{a.name}{a.field_type === "select" ? <select value={typeof attributeValues[a.id] === "string" ? attributeValues[a.id] as string : ""} onChange={(e) => setAttribute(a.id, e.target.value)} required={a.required}><option value="">Selecione</option>{optionsOf(a.options).map((o) => <option key={o} value={o}>{o}</option>)}</select> : a.field_type === "multiselect" ? <select multiple value={Array.isArray(attributeValues[a.id]) ? attributeValues[a.id] as string[] : []} onChange={(e) => setAttribute(a.id, Array.from(e.target.selectedOptions, (o) => o.value))}>{optionsOf(a.options).map((o) => <option key={o} value={o}>{o}</option>)}</select> : a.field_type === "boolean" ? <select value={typeof attributeValues[a.id] === "boolean" ? String(attributeValues[a.id]) : ""} onChange={(e) => setAttribute(a.id, e.target.value === "true")}><option value="">Selecione</option><option value="true">Sim</option><option value="false">Não</option></select> : a.field_type === "number" ? <input type="number" value={typeof attributeValues[a.id] === "number" || typeof attributeValues[a.id] === "string" ? String(attributeValues[a.id]) : ""} onChange={(e) => setAttribute(a.id, e.target.value === "" ? null : Number(e.target.value))} required={a.required} /> : a.field_type === "date" ? <input type="date" value={typeof attributeValues[a.id] === "string" ? attributeValues[a.id] as string : ""} onChange={(e) => setAttribute(a.id, e.target.value)} required={a.required} /> : <input value={typeof attributeValues[a.id] === "string" || typeof attributeValues[a.id] === "number" ? String(attributeValues[a.id]) : ""} onChange={(e) => setAttribute(a.id, e.target.value)} required={a.required} />}</label>)}</>}
    {active === "Serviços" && <><h2>Serviços</h2>{!categoryId ? <p className="fieldNote">Escolha uma categoria na apresentação.</p> : services.length === 0 ? <p className="fieldNote">Esta categoria ainda não possui serviços configurados.</p> : services.map((s) => <label key={s.id} className="serviceCheck"><span><input type="checkbox" checked={selectedServices[s.id] === true} onChange={(e) => toggleService(s.id, e.target.checked)} /> {s.name}{s.required ? " *" : ""}</span>{s.description && <small>{s.description}</small>}</label>)}<label>Observações sobre serviços<textarea value={servicesText} onChange={(e) => setServicesText(e.target.value)} rows={5} /></label></>}
    {active === "Preços" && <><h2>Preços</h2><label>Valor de referência<input value={price} onChange={(e) => setPrice(e.target.value)} inputMode="decimal" placeholder="0,00" /></label></>}
    {active === "Publicação" && <><h2>Publicação</h2><div className="publicationBox"><p>O anúncio será salvo como <strong>rascunho</strong>. A publicação deverá ocorrer somente após revisão e validação.</p></div></>}
    {error && <p className="formError">{error}</p>}{message && <p className="formSuccess">{message}</p>}<button className="primaryButton" disabled={busy}>{busy ? "Salvando..." : "Salvar rascunho"}</button></form></div></section></main>;
}
