"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/browser";

type Lead={id:string;name:string;email:string|null;phone:string|null;message:string|null;source:string;status:string;created_at:string};
const statusLabel:Record<string,string>={new:"Novo",contacted:"Em contato",closed:"Concluído",archived:"Arquivado"};
const sourceLabel:Record<string,string>={profile:"Perfil",service:"Serviço",event:"Evento",whatsapp:"WhatsApp"};

export default function ParceiroLeads(){
 const [venueId,setVenueId]=useState("");const [leads,setLeads]=useState<Lead[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return}const {data:v,error:e}=await s.from("partner_venues").select("id").eq("owner_user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(e)throw e;if(!v)throw new Error("Cadastre a casa antes de acessar os leads.");setVenueId(v.id);const {data,error:le}=await s.from("partner_venue_leads").select("id,name,email,phone,message,source,status,created_at").eq("venue_id",v.id).order("created_at",{ascending:false});if(le)throw le;setLeads((data||[]) as Lead[])}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar os leads."))},[]);
 async function changeStatus(id:string,status:string){setBusy(true);setError("");try{const {error}=await createClient().from("partner_venue_leads").update({status}).eq("id",id).eq("venue_id",venueId);if(error)throw error;await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível atualizar o lead.")}finally{setBusy(false)}}
 return <main className="shell"><nav className="topbar"><Link className="brand" href="/"><span className="brandMark">P</span><span>Pecatho</span></Link><div className="navLinks"><Link href="/painel/parceiro">Dados da casa</Link><Link href="/painel/parceiro/comercial">Comercial</Link><Link href="/painel/parceiro/midias">Galeria</Link><Link href="/parceiros">Vitrine</Link></div></nav><section className="hero"><div className="eyebrow">PARCEIROS · LEADS</div><h1>Solicitações comerciais.</h1><p className="heroCopy">Aqui ficam os contatos enviados pela vitrine pública da sua casa.</p>{error&&<p className="formError">{error}</p>}<section className="authCard">{leads.length===0?<div><h2>Nenhuma solicitação ainda.</h2><p style={{opacity:.75}}>Quando alguém demonstrar interesse pelo seu perfil, serviço ou evento, o contato aparecerá aqui.</p></div>:<div style={{display:"grid",gap:14}}>{leads.map(x=><article key={x.id} className="card"><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{x.name}</strong><div style={{opacity:.65,fontSize:13,marginTop:4}}>{sourceLabel[x.source]||x.source} · {new Date(x.created_at).toLocaleString("pt-BR")}</div></div><span>{statusLabel[x.status]||x.status}</span></div>{x.email&&<p>E-mail: {x.email}</p>}{x.phone&&<p>Telefone: {x.phone}</p>}{x.message&&<p style={{whiteSpace:"pre-wrap",opacity:.8}}>{x.message}</p>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}>{x.phone&&<a className="secondaryButton" href={"tel:"+x.phone}>Ligar</a>}{x.phone&&<a className="secondaryButton" href={"https://wa.me/"+x.phone.replace(/\D/g,"")} target="_blank" rel="noreferrer">WhatsApp</a>}{x.email&&<a className="secondaryButton" href={"mailto:"+x.email}>E-mail</a>}{x.status==="new"&&<button className="secondaryButton" disabled={busy} onClick={()=>void changeStatus(x.id,"contacted")}>Marcar em contato</button>}{x.status==="contacted"&&<button className="secondaryButton" disabled={busy} onClick={()=>void changeStatus(x.id,"closed")}>Concluir</button>}{x.status!=="archived"&&<button className="secondaryButton" disabled={busy} onClick={()=>void changeStatus(x.id,"archived")}>Arquivar</button>}{x.status==="archived"&&<button className="secondaryButton" disabled={busy} onClick={()=>void changeStatus(x.id,"new")}>Reabrir</button>}</div></article>)}</div>}</section></section></main>
}