"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/browser";

type Media={id:string;venue_id:string;kind:string;storage_bucket:string;storage_path:string;original_filename:string|null;moderation_status:string;rejection_reason:string|null};

export default function AdminParceiroMidias(){
 const [items,setItems]=useState<Media[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return}const {data,error:e}=await s.from("partner_venue_media").select("id,venue_id,kind,storage_bucket,storage_path,original_filename,moderation_status,rejection_reason").eq("moderation_status","pending").order("created_at",{ascending:true});if(e)throw e;setItems((data||[]) as Media[])}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar a fila."))},[]);
 async function moderate(item:Media,action:"approve"|"reject"){const reason=action==="reject"?window.prompt("Motivo da rejeição:"):"";if(action==="reject"&&!reason)return;setBusy(true);setError("");try{const {error:e}=await createClient().rpc("admin_moderate_partner_venue_media",{p_media_id:item.id,p_action:action,p_reason:reason||null});if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível moderar a mídia.")}finally{setBusy(false)}}
 return <main className="shell"><nav className="topbar"><Link className="brand" href="/admin"><span className="brandMark">P</span><span>Pecatho</span></Link><div className="navLinks"><Link href="/admin/parceiros">Parceiros</Link><Link href="/parceiros">Vitrine</Link></div></nav><section className="hero"><div className="eyebrow">ADMINISTRAÇÃO · MÍDIA DE PARCEIROS</div><h1>Fila de <em>moderação.</em></h1><p className="heroCopy">Aprove ou rejeite fotos e vídeos enviados pelas casas parceiras antes da publicação.</p>{error&&<p className="formError">{error}</p>}{items.length===0?<div className="card"><h2>Fila limpa</h2><p>Nenhuma mídia aguarda moderação.</p></div>:<section className="partnerGrid">{items.map(item=>{const url=createClient().storage.from(item.storage_bucket).getPublicUrl(item.storage_path).data.publicUrl;return <article className="card" key={item.id}>{item.kind==="image"?<img src={url} alt={item.original_filename||"Mídia do parceiro"} style={{width:"100%",aspectRatio:"16/10",objectFit:"cover",borderRadius:12}}/>:<video src={url} controls style={{width:"100%",aspectRatio:"16/10",objectFit:"cover",borderRadius:12}}/>}<h2>{item.original_filename||"Mídia"}</h2><p className="fieldNote">Status: em moderação</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="primaryButton" disabled={busy} onClick={()=>void moderate(item,"approve")}>Aprovar</button><button className="secondaryButton" disabled={busy} onClick={()=>void moderate(item,"reject")}>Rejeitar</button></div></article>})}</section>}</section></main>
}