import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

export default async function Painel() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const { data: profile } = await supabase.from("profiles").select("display_name,username,status,account_type").eq("id", user.id).single();
  if (profile?.account_type === "customer") redirect("/painel/cliente");
  const { data: advertiser } = await supabase.from("advertiser_profiles").select("id,title,status,verification_status,city_id,state_id").eq("user_id", user.id).maybeSingle();
  const { data: creator } = await supabase.from("fans_creators").select("id,slug,display_name,status,bio").eq("user_id", user.id).maybeSingle();
  const { count: followingCount } = await supabase.from("user_follows").select("profile_id", { count: "exact", head: true }).eq("follower_id", user.id);
  const { count: unreadNotifications } = await supabase.from("fans_notifications").select("id", { count: "exact", head: true }).eq("user_id", user.id).is("read_at", null);
  const { count: conversationCount } = await supabase.from("conversation_members").select("conversation_id", { count: "exact", head: true }).eq("user_id", user.id);
  const { data: receivedGifts } = await supabase.from("pecatho_gifts").select("id,amount,status,recipient_type,created_at").eq("recipient_user_id", user.id).order("created_at", { ascending: false }).limit(8);
  const publicationStatus: Record<string, string> = { draft: "Rascunho", pending_review: "Em análise", published: "Publicado", paused: "Pausado", suspended: "Suspenso", archived: "Arquivado" };
  const verificationStatus: Record<string, string> = { unverified: "Não verificada", pending: "Em análise", verified: "Verificada", rejected: "Rejeitada", expired: "Expirada" };
  const creatorStatus: Record<string, string> = { active: "Ativo", suspended: "Suspenso", inactive: "Inativo" };
  const paidReceivedGifts = (receivedGifts ?? []).filter((gift) => gift.status === "paid");
  const receivedGiftTotal = paidReceivedGifts.reduce((sum, gift) => sum + Number(gift.amount || 0), 0);
  return (
    <main className="shell advertiserDashboard"><nav className="topbar"><div className="brand"><span className="brandMark">P</span><span>Pecatho</span></div><div className="navLinks"><Link href="/">Página inicial</Link><Link href="/anunciantes">Anunciantes</Link><Link href="/admin" className="navCta">Administração</Link></div></nav>
      <section className="hero"><nav className="dashboardSectionNav" aria-label="Navegação rápida do painel"><Link href="#operacao">Operação</Link><Link href="#relacionamento">Relacionamento</Link><Link href="#financeiro">Financeiro</Link><Link href="#conta">Conta</Link></nav><div className="eyebrow">PECATHO · ÁREA DO ANUNCIANTE</div><h1>Olá, <em>{profile?.display_name || user.email}</em></h1><p className="heroCopy">Sua central de operação reúne anúncio, mídia, disponibilidade, relacionamento e Pecatho Fans em uma única experiência.</p><div className="dashboardQuickLinks"><Link href="/anunciantes">Explorar vitrine</Link><Link href="/painel/financeiro">Financeiro</Link>{advertiser&&<Link href="/anunciantes">Ver meu posicionamento</Link>}<Link href="/fans">Pecatho Fans</Link><Link href="/parceiros">Parceiros</Link><Link href="/painel/mensagens">Mensagens</Link></div>
        <section id="operacao" className="pillars">
          <article className="card"><div className="cardIcon">A</div><h2>Meu anúncio Pecatho</h2><p>{advertiser ? advertiser.title : "Você ainda não criou um anúncio de serviços."}</p><p>Status: {advertiser ? publicationStatus[advertiser.status] || advertiser.status : "Não iniciado"}</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><Link className="secondaryButton" href="/painel/anuncio">{advertiser ? "Editar anúncio" : "Criar anúncio"}</Link>{advertiser&&<Link className="secondaryButton" href="/painel/anuncio/operacional">Disponibilidade, preços e pagamentos</Link>}{advertiser&&<Link className="secondaryButton" href="/painel/anuncio/revisao">Revisar antes de enviar</Link>}</div></article>
          <article className="card"><div className="cardIcon">V</div><h2>Verificação do anúncio</h2><p>{advertiser ? verificationStatus[advertiser.verification_status] || advertiser.verification_status : "Não há anúncio para verificar."}</p>{advertiser&&<Link className="secondaryButton" href="/painel/anuncio/revisao">Conferir pendências</Link>}</article>
          {advertiser&&<article className="card"><div className="cardIcon">M</div><h2>Fotos e vídeos</h2><p>Defina, mídia por mídia, o que será público e o que ficará protegido por pagamento.</p><Link className="secondaryButton" href="/painel/anuncio/midias">Gerenciar acesso às mídias</Link></article>}
          <article className="card"><div className="cardIcon">F</div><h2>Meu Fans</h2><p>{creator?`${creator.display_name} · ${creatorStatus[creator.status]||creator.status}`:"Você pode vender conteúdo sem possuir um anúncio de serviços."}</p><Link className="secondaryButton" href="/fans">{creator?"Abrir Fans":"Criar perfil Fans"}</Link></article>
          <article className="card"><div className="cardIcon">C</div><h2>Conteúdo comercial</h2><p>Venda imagens, vídeos e pacotes digitais com preço definido por você, em uma biblioteca privada.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{advertiser&&<Link className="secondaryButton" href="/painel/conteudos">Loja do anúncio</Link>}<Link className="secondaryButton" href="/fans/gerenciar/conteudos">Loja Fans</Link></div></article>
          <article className="card"><div className="cardIcon">🎁</div><h2>Presentes recebidos</h2><p className="financeBig">{paidReceivedGifts.length}</p><p>{receivedGiftTotal.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })} em presentes confirmados.</p><p className="fieldNote">Os valores recebidos entram no ciclo financeiro após a confirmação do pagamento.</p></article>
          <article id="relacionamento" className="card"><div className="cardIcon">✉</div><h2>Minhas conversas</h2><p>{conversationCount ?? 0} {(conversationCount ?? 0) === 1 ? "conversa ativa" : "conversas ativas"} com perfis do Pecatho.</p><p className="fieldNote">Inicie uma conversa diretamente na página pública de um anunciante.</p><Link className="secondaryButton" href="/painel/mensagens">Abrir mensagens</Link></article>
          <article className="card"><div className="cardIcon">★</div><h2>Perfis acompanhados</h2><p>{followingCount ?? 0} {(followingCount ?? 0) === 1 ? "perfil" : "perfis"} na sua lista pessoal.</p><p className="fieldNote">Acompanhe anunciantes para encontrá-los novamente com facilidade.</p><Link className="secondaryButton" href="/painel/seguindo">Ver meus acompanhamentos</Link></article>
          <article className="card"><div className="cardIcon">N</div><h2>Notificações</h2><p>{unreadNotifications ?? 0} {(unreadNotifications ?? 0) === 1 ? "notificação não lida" : "notificações não lidas"}.</p><p className="fieldNote">Veja atividades importantes da sua conta e marque-as como lidas.</p><Link className="secondaryButton" href="/painel/notificacoes">Abrir central de atividade</Link></article>
          <article className="card"><div className="cardIcon">B</div><h2>Minha casa / parceiro</h2><p>Cadastre uma boate, casa noturna, bar, lounge ou espaço de eventos para entrar na vitrine comercial do Pecatho.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="secondaryButton" href="/painel/parceiro">Dados da casa</Link><Link className="secondaryButton" href="/painel/parceiro/midias">Galeria</Link><Link className="secondaryButton" href="/painel/parceiro/comercial">Comercial</Link><Link className="secondaryButton" href="/painel/parceiro/leads">Leads</Link></div></article><article className="card"><div className="cardIcon">L</div><h2>Localização</h2><p>Estados e municípios oficiais da base territorial do Pecatho.</p>{advertiser?<Link className="secondaryButton" href="/painel/anuncio">Editar localização</Link>:<span className="fieldNote">Disponível ao criar o anúncio.</span>}</article>
          <article id="financeiro" className="card"><div className="cardIcon">R$</div><h2>Financeiro e recebimentos</h2><p>Consulte o saldo das vendas digitais do anúncio, acompanhe solicitações e peça o recebimento do valor disponível.</p><Link className="secondaryButton" href="/painel/financeiro">Abrir financeiro</Link></article>
          <article id="conta" className="card"><div className="cardIcon">P</div><h2>Perfil da conta</h2><p>{profile?.status === "active" ? "Conta ativa" : "Conta em configuração"}</p><p className="fieldNote">Edite seus dados pessoais, endereço e preferências cadastrais.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:16}}><Link className="secondaryButton" href="/painel/perfil">Editar meus dados</Link><Link className="secondaryButton" href="/admin">Administração</Link></div></article>
        </section><nav className="dashboardMobileNav" aria-label="Acesso rápido"><Link href="/painel/anuncio">Anúncio</Link><Link href="/fans">Fans</Link><Link href="/painel/mensagens">Mensagens</Link><Link href="/painel/financeiro">Financeiro</Link></nav>
      </section></main>
  );
}
